libCommons:
  RemoteConfig:
    PlistFile: "Local.kb"
    PlistUrl: ""
  Analytics:
      FlurryKey: "GTJN395TKWN6T8T6YKC3"
      FacebookID: "910238615719294"
      TapJoySDKKey: "Y5_zVkZeSreG2Z7B_wtM8gECBliMafnGOk44En6LHlqRPGoWow2uhWFacJZj"
      FlyerKey: "d4VKN2yBPk7gqTRBZcwkbc"
      GoogleTrackerID: "UA-64233211-2"
      FlurryStoredMaxCount: 1000
  DiverseSession:
    AppManageDiverseSession: true

  Market:
    DefaultMarket: "Google"
    Markets:
      Google:
        AppPackage: "com.android.vending"
        AppUrl: "market://details?id="
        WebUrl: "https://play.google.com/store/apps/details?id="
      Amazon:
        AppPackage: "com.amazon.venezia"
        AppUrl: "amzn://apps/android?p="
        WebUrl: "http://www.amazon.com/gp/mas/dl/android?p="
  Connection:
    SigKey: "603_2"
    HashKey: "x5UJ~fb}3_Dma>l B]YB/?'1As[\"E<I!"
libFramework:
  Push:
    SenderID: ""
    SendTokenToServer: yes
  Alerts:
    LocalFile: "Alerts.kb"
    RemoteUrl: ""

libIAP:
  Verify:
    ByDevice:
      SignatureKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnHCQTYWS0OnyHjO/yl+RQ5sFZ3eqpgilg0856s86qiZsAmTmLRB1M5dik2p4oO6HMyLQNScY2e6y0erpbq6YmLdG4kLclDb7+T71/0WsXik49HCDv7nI7i/bxywkgYqjtew3sGj99mhDvdCU3+5BnITGKAOJwjxq6N1sw0ork3KxPo3QpFUCPpqo2CPKctEJgJEbxYhIatPQoN3GyJPtiGFSu62nxVr/tqyUkEAKJtAOjqqoEQ6BhdGN7PY/GOe+N+2T5PsNKdltoBd/zobybvH9o4uOrfDTMM7Z1C6Ocgm+nmdWs0FgRuTgZp7LtS4QThdaUuSRDeW5cvvg40TeOQIDAQAB"

libKeyboard:
  DictionaryUrl: "http://emojidevelop.s3.amazonaws.com/AndroidResource/languages/"